repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.35.0'
    hooks:
    -   id: eslint
        types: [ file ]
        types_or: [ javascript, jsx, ts, tsx, vue ]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
        - id: prettier
          types: [ file ]
          types_or: [ javascript, jsx, ts, tsx, vue ]
